import { Inter } from "next/font/google";
import "./globals.css";
import { Flip, ToastContainer } from "react-toastify";

const fontInter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  preload: true,
  weight: ["300", "400", "500", "600", "700", "800"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className={`${fontInter.variable}`} lang="en">
      <body>
        {children}
        <ToastContainer
          position="top-center"
          autoClose={2000}
          hideProgressBar
          newestOnTop={false}
          closeOnClick={false}
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="colored"
          transition={Flip}
        />
      </body>
    </html>
  );
}
